nome = str(input('Digite um nome: ')).strip()
prime = nome.split()
print('O nome digitado foi {}'.format(nome))
print('O primeiro nome é {}'.format(prime[0]))
print('O útimo nome é {}'.format(prime[-1]))
